const myPlaylist = [
    { name: "Hame Tumse Hua Hai Payar", artist: "Artist Name", audio: "song1.mp3", cover: "song1.jpg" },
    { name: "Pahli Pahli Bar Mahobbat Ki Hai", artist: "Artist Name", audio: "song2.mp3", cover: "song2.jpg" },
    { name: "Oye Raju Payar Na Kariyo", artist: "Artist Name", audio: "song3.mp3", cover: "song3.jpg" },
    { name: "Kuon Ki Itna Pyar", artist: "Artist Name", audio: "song4.mp3", cover: "song4.jpg" },
    { name: "Do Lafzon Me", artist: "Artist Name", audio: "song5.mp3", cover: "song5.jpg" },
    { name: "Kyo kisi ko ( tere nam ) ", artist: "Artist Name", audio: "song6.mp3", cover: "song6.jpg" },
    { name: "Ek Dilruba Hai", artist: "Artist Name", audio: "song7.mp3", cover: "song7.jpg" },
    { name: "Dil Ke Badle Sanam", artist: "Artist Name", audio: "song8.mp3", cover: "song8.jpg" },
    { name: "Husan Hai Suhana ", artist: "Artist Name", audio: "song9.mp3", cover: "song9.jpg" },
    { name: "Soan Kitna Sona Hai", artist: "Artist Name", audio: "song10.mp3", cover: "song10.jpg" },
    { name: "Mahobbat Ki Nhi Jati ", artist: "Artist Name", audio: "song11.mp3", cover: "song11.jpg" },
    { name: "Callage Ki Natkhai Callage Ki Ladkiyon", artist: "Artist Name", audio: "song12.mp3", cover: "song12.jpg" },
    { name: "Saat Samundar Par", artist: "Artist Name", audio: "song13.mp3", cover: "song13.jpg" },
    { name: "Mera Dil jis Dil pe Fida Hai", artist: "Artist Name", audio: "song14.mp3", cover: "song14.jpg" },
    { name: "Oh Oh Jane Jana", artist: "Artist Name", audio: "song15.mp3", cover: "song15.jpg" },
    { name: "Chunri Chunri", artist: "Artist Name", audio: "song16.mp3", cover: "song16.jpg" },
    { name: "Ye Dil Diwana", artist: "Artist Name", audio: "song17.mp3", cover: "song17.jpg" },
    { name: "Aksar is duniya mein", artist: "Artist Name", audio: "song18.mp3", cover: "song18.jpg" },
    { name: "Qayamat Qayamat", artist: "Artist Name", audio: "song19.mp3", cover: "song19.jpg" },
    { name: "Aaye Ho Meri zindagi mein", artist: "Artist Name", audio: "song20.mp3", cover: "song20.jpg" },
    { name: "Hum tumko nigahon mein", artist: "Artist Name", audio: "song21.mp3", cover: "song21.jpg" },
    { name: "Chand sifarish", artist: "Artist Name", audio: "song22.mp3", cover: "song22.jpg" },
    { name: "bole chudiyan", artist: "Artist Name", audio: "song23.mp3", cover: "song23.jpg" },
    { name: "Teri chunariya", artist: "Artist Name", audio: "song24.mp3", cover: "song24.jpg" },
    { name: "Aankh Hai Bhari Bhari", artist: "Artist Name", audio: "song25.mp3", cover: "song25.jpg" },
    { name: "barsat ke Mausam mein", artist: "Artist Name", audio: "song26.mp3", cover: "song26.jpg" },
    { name: "Koi jaaye to Le Aaye", artist: "Artist Name", audio: "song27.mp3", cover: "song27.jpg" },
    { name: "Pardesi Pardesi mere", artist: "Artist Name", audio: "song28.mp3", cover: "song28.jpg" },
    { name: "shikwa nahi Kisi Se", artist: "Artist Name", audio: "song29.mp3", cover: "song29.jpg" },
    { name: "Tu pyar Hai Kisi aur ka", artist: "Artist Name", audio: "song30.mp3", cover: "song30.jpg" },
    { name: "jo bhi kasmen", artist: "Artist Name", audio: "song31.mp3", cover: "song31.jpg" },
    { name: "....name ....", artist: "Artist Name", audio: "song32.mp3", cover: "song32.jpg" },
    { name: "....name ....", artist: "Artist Name", audio: "song33.mp3", cover: "song33.jpg" },
    { name: "....name ....", artist: "Artist Name", audio: "song34.mp3", cover: "song34.jpg" },
    { name: "....name ....", artist: "Artist Name", audio: "song35.mp3", cover: "song35.jpg" },
    { name: "....name ....", artist: "Artist Name", audio: "song36.mp3", cover: "song36.jpg" },
    { name: "....name ....", artist: "Artist Name", audio: "song37.mp3", cover: "song37.jpg" },
    { name: "....name ....", artist: "Artist Name", audio: "song38.mp3", cover: "song38.jpg" },
    { name: "....name ....", artist: "Artist Name", audio: "song39.mp3", cover: "song39.jpg" },
    { name: "....name ....", artist: "Artist Name", audio: "song40.mp3", cover: "song40.jpg" },
    { name: "....name ....", artist: "Artist Name", audio: "song41.mp3", cover: "song41.jpg" },
    { name: "....name ....", artist: "Artist Name", audio: "song42.mp3", cover: "song42.jpg" },
    { name: "....name ....", artist: "Artist Name", audio: "song43.mp3", cover: "song43.jpg" },
    { name: "....name ....", artist: "Artist Name", audio: "song44.mp3", cover: "song44.jpg" },
    { name: "....name ....", artist: "Artist Name", audio: "song45.mp3", cover: "song45.jpg" },
    { name: "....name ....", artist: "Artist Name", audio: "song46.mp3", cover: "song46.jpg" },
    { name: "....name ....", artist: "Artist Name", audio: "song47.mp3", cover: "song47.jpg" },
    { name: "....name ....", artist: "Artist Name", audio: "song48.mp3", cover: "song48.jpg" },
    { name: "....name ....", artist: "Artist Name", audio: "song49.mp3", cover: "song49.jpg" },
    { name: "....name ....", artist: "Artist Name", audio: "song50.mp3", cover: "song50.jpg" },
    { name: "....name ....", artist: "Artist Name", audio: "song51.mp3", cover: "song51.jpg" },
    { name: "....name ....", artist: "Artist Name", audio: "song52.mp3", cover: "song52.jpg" },
    { name: "....name ....", artist: "Artist Name", audio: "song53.mp3", cover: "song53.jpg" },
    { name: "....name ....", artist: "Artist Name", audio: "song54.mp3", cover: "song54.jpg" },
    { name: "....name ....", artist: "Artist Name", audio: "song55.mp3", cover: "song55.jpg" },
    { name: "....name ....", artist: "Artist Name", audio: "song56.mp3", cover: "song56.jpg" },
    { name: "....name ....", artist: "Artist Name", audio: "song57.mp3", cover: "song57.jpg" },
    { name: "....name ....", artist: "Artist Name", audio: "song58.mp3", cover: "song58.jpg" },
    { name: "....name ....", artist: "Artist Name", audio: "song59.mp3", cover: "song59.jpg" },
    { name: "....name ....", artist: "Artist Name", audio: "song60.mp3", cover: "song60.jpg" },
    { name: "....name ....", artist: "Artist Name", audio: "song61.mp3", cover: "song61.jpg" },
    { name: "....name ....", artist: "Artist Name", audio: "song62.mp3", cover: "song62.jpg" },
    { name: "....name ....", artist: "Artist Name", audio: "song63.mp3", cover: "song63.jpg" },
    { name: "....name ....", artist: "Artist Name", audio: "song64.mp3", cover: "song64.jpg" },
    { name: "....name ....", artist: "Artist Name", audio: "song65.mp3", cover: "song65.jpg" },
    { name: "....name ....", artist: "Artist Name", audio: "song66.mp3", cover: "song66.jpg" },
    { name: "....name ....", artist: "Artist Name", audio: "song67.mp3", cover: "song67.jpg" },
    { name: "....name ....", artist: "Artist Name", audio: "song68.mp3", cover: "song68.jpg" },
    { name: "....name ....", artist: "Artist Name", audio: "song69.mp3", cover: "song69.jpg" },
    { name: "....name ....", artist: "Artist Name", audio: "song70.mp3", cover: "song70.jpg" },
    { name: "....name ....", artist: "Artist Name", audio: "song71.mp3", cover: "song71.jpg" },
    { name: "....name ....", artist: "Artist Name", audio: "song72.mp3", cover: "song72.jpg" },
    { name: "....name ....", artist: "Artist Name", audio: "song73.mp3", cover: "song73.jpg" },
    { name: "....name ....", artist: "Artist Name", audio: "song74.mp3", cover: "song74.jpg" },
    { name: "....name ....", artist: "Artist Name", audio: "song75.mp3", cover: "song75.jpg" },
    { name: "....name ....", artist: "Artist Name", audio: "song76.mp3", cover: "song76.jpg" },
    { name: "....name ....", artist: "Artist Name", audio: "song77.mp3", cover: "song77.jpg" },
    { name: "....name ....", artist: "Artist Name", audio: "song78.mp3", cover: "song78.jpg" },
    { name: "....name ....", artist: "Artist Name", audio: "song79.mp3", cover: "song79.jpg" },
    { name: "....name ....", artist: "Artist Name", audio: "song80.mp3", cover: "song80.jpg" },
    { name: "....name ....", artist: "Artist Name", audio: "song81.mp3", cover: "song81.jpg" },
    { name: "....name ....", artist: "Artist Name", audio: "song82.mp3", cover: "song82.jpg" },
    { name: "....name ....", artist: "Artist Name", audio: "song83.mp3", cover: "song83.jpg" },
    { name: "....name ....", artist: "Artist Name", audio: "song84.mp3", cover: "song84.jpg" },
    { name: "....name ....", artist: "Artist Name", audio: "song85.mp3", cover: "song85.jpg" },
    { name: "....name ....", artist: "Artist Name", audio: "song86.mp3", cover: "song86.jpg" },
    { name: "....name ....", artist: "Artist Name", audio: "song87.mp3", cover: "song87.jpg" },
    { name: "....name ....", artist: "Artist Name", audio: "song88.mp3", cover: "song88.jpg" },
    { name: "....name ....", artist: "Artist Name", audio: "song89.mp3", cover: "song89.jpg" },
    { name: "....name ....", artist: "Artist Name", audio: "song90.mp3", cover: "song90.jpg" },
    { name: "....name ....", artist: "Artist Name", audio: "song91.mp3", cover: "song91.jpg" },
    { name: "....name ....", artist: "Artist Name", audio: "song92.mp3", cover: "song92.jpg" },
    { name: "....name ....", artist: "Artist Name", audio: "song93.mp3", cover: "song93.jpg" },
    { name: "....name ....", artist: "Artist Name", audio: "song94.mp3", cover: "song94.jpg" },
    { name: "....name ....", artist: "Artist Name", audio: "song95.mp3", cover: "song95.jpg" },
    { name: "....name ....", artist: "Artist Name", audio: "song96.mp3", cover: "song96.jpg" },
    { name: "....name ....", artist: "Artist Name", audio: "song97.mp3", cover: "song97.jpg" },
    { name: "....name ....", artist: "Artist Name", audio: "song98.mp3", cover: "song98.jpg" },
    { name: "....name ....", artist: "Artist Name", audio: "song99.mp3", cover: "song99.jpg" },
    { name: "....name ....", artist: "Artist Name", audio: "song100.mp3", cover: "song100.jpg" }
];
