const myPlaylist = [
    { name: "Hame Tumse Hua Hai Payar", artist: "Artist Name", audio: "song1.mp3", cover: "song1.jpg" },
    { name: "Pahli Pahli Bar Mahobbat Ki Hai", artist: "Artist Name", audio: "song2.mp3", cover: "song2.jpg" },
    { name: "Oye Raju Payar Na Kariyo", artist: "Artist Name", audio: "song3.mp3", cover: "song3.jpg" },
    { name: "Kuon Ki Itna Pyar", artist: "Artist Name", audio: "song4.mp3", cover: "song4.jpg" },
    { name: "Do Lafzon Me", artist: "Artist Name", audio: "song5.mp3", cover: "song5.jpg" },
    { name: "Kyo kisi ko ( tere nam ) ", artist: "Artist Name", audio: "song6.mp3", cover: "song6.jpg" },
    { name: "Ek Dilruba Hai", artist: "Artist Name", audio: "song7.mp3", cover: "song7.jpg" },
    { name: "Dil Ke Badle Sanam", artist: "Artist Name", audio: "song8.mp3", cover: "song8.jpg" },
    { name: "Husan Hai Suhana ", artist: "Artist Name", audio: "song9.mp3", cover: "song9.jpg" },
    { name: "Soan Kitna Sona Hai", artist: "Artist Name", audio: "song10.mp3", cover: "song10.jpg" },
    { name: "Mahobbat Ki Nhi Jati ", artist: "Artist Name", audio: "song11.mp3", cover: "song11.jpg" },
    { name: "Callage Ki Natkhai Callage Ki Ladkiyon", artist: "Artist Name", audio: "song12.mp3", cover: "song12.jpg" },
    { name: "Saat Samundar Par", artist: "Artist Name", audio: "song13.mp3", cover: "song13.jpg" },
    { name: "Mera Dil jis Dil pe Fida Hai", artist: "Artist Name", audio: "song14.mp3", cover: "song14.jpg" },
    { name: "Oh Oh Jane Jana", artist: "Artist Name", audio: "song15.mp3", cover: "song15.jpg" },
    { name: "Chunri Chunri", artist: "Artist Name", audio: "song16.mp3", cover: "song16.jpg" },
    { name: "Ye Dil Diwana", artist: "Artist Name", audio: "song17.mp3", cover: "song17.jpg" },
    { name: "Aksar is duniya mein", artist: "Artist Name", audio: "song18.mp3", cover: "song18.jpg" },
    { name: "Qayamat Qayamat", artist: "Artist Name", audio: "song19.mp3", cover: "song19.jpg" },
    { name: "Aaye Ho Meri zindagi mein", artist: "Artist Name", audio: "song20.mp3", cover: "song20.jpg" },
    { name: "Hum tumko nigahon mein", artist: "Artist Name", audio: "song21.mp3", cover: "song21.jpg" },
    { name: "Chand sifarish", artist: "Artist Name", audio: "song22.mp3", cover: "song22.jpg" },
    { name: "bole chudiyan", artist: "Artist Name", audio: "song23.mp3", cover: "song23.jpg" },
    { name: "Teri chunariya", artist: "Artist Name", audio: "song24.mp3", cover: "song24.jpg" },
    { name: "Aankh Hai Bhari Bhari", artist: "Artist Name", audio: "song25.mp3", cover: "song25.jpg" },
    { name: "barsat ke Mausam mein", artist: "Artist Name", audio: "song26.mp3", cover: "song26.jpg" },
    { name: "Koi jaaye to Le Aaye", artist: "Artist Name", audio: "song27.mp3", cover: "song27.jpg" },
    { name: "Pardesi Pardesi mere", artist: "Artist Name", audio: "song28.mp3", cover: "song28.jpg" },
    { name: "shikwa nahi Kisi Se", artist: "Artist Name", audio: "song29.mp3", cover: "song29.jpg" },
    { name: "Tu pyar Hai Kisi aur ka", artist: "Artist Name", audio: "song30.mp3", cover: "song30.jpg" },
    { name: "jo bhi kasmen", artist: "Artist Name", audio: "song31.mp3", cover: "song31.jpg" },
    { name: "Pa Liya Hai pyar Tera", artist: "Artist Name", audio: "song32.mp3", cover: "song32.jpg" },
    { name: "na Milo humse jyada", artist: "Artist Name", audio: "song33.mp3", cover: "song33.jpg" },
    { name: "had Kar Di aapane", artist: "Artist Name", audio: "song34.mp3", cover: "song34.jpg" },
    { name: "Main agar samne", artist: "Artist Name", audio: "song35.mp3", cover: "song35.jpg" },
    { name: "aapke pyar mein", artist: "Artist Name", audio: "song36.mp3", cover: "song36.jpg" },
    { name: "Vo ladki bahut yad aati hai", artist: "Artist Name", audio: "song37.mp3", cover: "song37.jpg" },
    { name: "Sham bhi khoob Hai", artist: "Artist Name", audio: "song38.mp3", cover: "song38.jpg" },
    { name: " Dil kahta Hai", artist: "Artist Name", audio: "song39.mp3", cover: "song39.jpg" },
    { name: " Tu pyar Hai Kisi aur ka", artist: "Artist Name", audio: "song40.mp3", cover: "song40.jpg" },
    { name: "Mohabbat Dil ka sukun Hai", artist: "Artist Name", audio: "song41.mp3", cover: "song41.jpg" },
    { name: "kaho Na kaho", artist: "Artist Name", audio: "song42.mp3", cover: "song42.jpg" },
    { name: "Dil Mera Tod Diya", artist: "Artist Name", audio: "song43.mp3", cover: "song43.jpg" },
    { name: "mere rang mein rangne wali", artist: "Artist Name", audio: "song44.mp3", cover: "song44.jpg" },
    { name: "chura ke Dil Mera", artist: "Artist Name", audio: "song45.mp3", cover: "song45.jpg" },
    { name: "aankhon Se tune yah kya", artist: "Artist Name", audio: "song46.mp3", cover: "song46.jpg" },
    { name: "Ham yaar Hain tumhare", artist: "Artist Name", audio: "song47.mp3", cover: "song47.jpg" },
    { name: "to chalun", artist: "Artist Name", audio: "song48.mp3", cover: "song48.jpg" },
    { name: "jindagi Ki talash mein ham", artist: "Artist Name", audio: "song49.mp3", cover: "song49.jpg" },
    { name: "sochenge tumhen pyar", artist: "Artist Name", audio: "song50.mp3", cover: "song50.jpg" },
    