const ytPlaylist = [
    { name: "Hame Tumse Hua Hai Pyaar", artist: "Udit Narayan & Alka Yagnik", ytId: "9T4p8s_V98U" },
    { name: "Pahli Pahli Bar Mohabbat Ki Hai", artist: "Kumar Sanu & Alka Yagnik", ytId: "1p3E7Q8w10A" },
    { name: "Oye Raju Pyaar Na Kariyo", artist: "Kumar Sanu", ytId: "Sg_C-QvS9uY" },
    { name: "Kyon Ki Itna Pyar", artist: "Udit Narayan & Alka Yagnik", ytId: "Gq-d_Q6d_W8" },
    { name: "Do Lafzon Mein", artist: "Babul Supriyo & Anuradha Paudwal", ytId: "4E8nK_P622E" },
    { name: "Kyo Kisi Ko (Tere Naam)", artist: "Udit Narayan", ytId: "v8bZ49L-dYw" },
    { name: "Ek Dilruba Hai", artist: "Udit Narayan", ytId: "X8K1g8M9t_A" },
    { name: "Dil Ke Badle Sanam", artist: "Udit Narayan & Alka Yagnik", ytId: "_eD8m8S2_vM" },
    { name: "Husn Hai Suhana", artist: "Abhijeet & Chandana Dixit", ytId: "_7sD2uG79G8" },
    { name: "Sona Kitna Sona Hai", artist: "Udit Narayan & Poornima", ytId: "jS3qY4W-3mE" },
    { name: "Mohabbat Ki Nahi Jati", artist: "Udit Narayan & Sadhana Sargam", ytId: "M_gL0M1_1_A" },
    { name: "College Ki Natkhat Ladkiyon", artist: "Udit Narayan", ytId: "p8F1l2m3N4O" },
    { name: "Saat Samundar Par", artist: "Sadhana Sargam", ytId: "7jP_f9v2X8E" },
    { name: "Mera Dil Jis Dil Pe Fida Hai", artist: "Udit Narayan & Alka Yagnik", ytId: "A0p9x9Q-A0A" },
    { name: "O O Jaane Jaana", artist: "Kamaal Khan", ytId: "x_elT6zkqGE" },
    { name: "Chunri Chunri", artist: "Abhijeet & Anuradha Sriram", ytId: "0pX2X9mK30w" },
    { name: "Ye Dil Deewana", artist: "Sonu Nigam", ytId: "B_48zM9Vp98" },
    { name: "Aksar Is Duniya Mein", artist: "Alka Yagnik", ytId: "f0g1W7A7CBA" },
    { name: "Qayamat Qayamat", artist: "Sonu Nigam & Alka Yagnik", ytId: "q8L1M9f8tA0" },
    { name: "Aaye Ho Meri Zindagi Mein", artist: "Udit Narayan", ytId: "c8L1M9f8tA0" },
    { name: "Hum Tumko Nigahon Mein", artist: "Udit Narayan & Shreya Ghoshal", ytId: "v0g1W7A7CBA" },
    { name: "Chand Sifarish", artist: "Shaan & Kailash Kher", ytId: "zWEOx7TS53U" },
    { name: "Bole Chudiyan", artist: "Kavita Krishnamurthy, Sonu Nigam & Alka Yagnik", ytId: "IBvg3WeqP1U" },
    { name: "Teri Chunariya", artist: "Kumar Sanu & Alka Yagnik", ytId: "g8L1M9f8tA0" },
    { name: "Aankh Hai Bhari Bhari", artist: "Kumar Sanu", ytId: "v8bZ49L-dYw" },
    { name: "Barsaat Ke Mausam Mein", artist: "Kumar Sanu & Roop Kumar Rathod", ytId: "vLzG8Z_4K9U" },
    { name: "Koi Jaaye To Le Aaye", artist: "Shankar Mahadevan & Alka Yagnik", ytId: "d_jE8L9f8tA" },
    { name: "Pardesi Pardesi Mere", artist: "Udit Narayan & Alka Yagnik", ytId: "_7sD2uG79G8" },
    { name: "Shikwa Nahi Kisi Se", artist: "Kumar Sanu", ytId: "Wd10Xm4E-o0" },
    { name: "Tu Pyar Hai Kisi Aur Ka", artist: "Kumar Sanu & Anuradha Paudwal", ytId: "4E8nK_P622E" },
    { name: "Jo Bhi Kasmein", artist: "Udit Narayan & Alka Yagnik", ytId: "B72_HsUR0Vc" },
    { name: "Pa Liya Hai Pyar Tera", artist: "Udit Narayan & Alka Yagnik", ytId: "Sg_C-QvS9uY" },
    { name: "Na Milo Humse Jyada", artist: "Sonu Nigam & Kavita Krishnamurthy", ytId: "qA3W3X8p-o0" },
    { name: "Hadd Kar Di Aapne", artist: "Udit Narayan & Kavita Krishnamurthy", ytId: "X8K1g8M9t_A" },
    { name: "Main Agar Saamne", artist: "Abhijeet & Alka Yagnik", ytId: "_eD8m8S2_vM" },
    { name: "Aapke Pyaar Mein", artist: "Alka Yagnik", ytId: "jS3qY4W-3mE" },
    { name: "Woh Ladki Bahut Yaad Aati Hai", artist: "Kumar Sanu & Alka Yagnik", ytId: "M_gL0M1_1_A" },
    { name: "Shaam Bhi Khoob Hai", artist: "Kumar Sanu, Udit Narayan & Alka Yagnik", ytId: "p8F1l2m3N4O" },
    { name: "Dil Kehta Hai", artist: "Kumar Sanu & Alka Yagnik", ytId: "7jP_f9v2X8E" },
    { name: "Mohabbat Dil Ka Sakoon", artist: "Kumar Sanu, Udit Narayan & Alka Yagnik", ytId: "A0p9x9Q-A0A" },
    { name: "Kaho Na Kaho", artist: "Amir Jamal", ytId: "x_elT6zkqGE" },
    { name: "Dil Mera Tod Diya", artist: "Alka Yagnik", ytId: "0pX2X9mK30w" },
    { name: "Mere Rang Mein Rangne Wali", artist: "S. P. Balasubrahmanyam", ytId: "B_48zM9Vp98" },
    { name: "Chura Ke Dil Mera", artist: "Kumar Sanu & Alka Yagnik", ytId: "f0g1W7A7CBA" },
    { name: "Aankhon Se Tune Yeh Kya", artist: "Kumar Sanu & Alka Yagnik", ytId: "q8L1M9f8tA0" },
    { name: "Hum Yaar Hain Tumhare", artist: "Udit Narayan & Alka Yagnik", ytId: "c8L1M9f8tA0" },
    { name: "To Chalun", artist: "Roop Kumar Rathod", ytId: "v0g1W7A7CBA" },
    { name: "Zindagi Ki Talash Mein", artist: "Kumar Sanu", ytId: "zWEOx7TS53U" },
    { name: "Sochenge Tumhe Pyaar", artist: "Kumar Sanu", ytId: "IBvg3WeqP1U" }
];
